In [2]:
#1.1 Создайте одномерный массив из чисел от 1 до 20 включительно. Выведите его форму
import numpy as np
arr = np.arange(1, 21)
print("Массив:", arr)
print("Форма массива:", arr.shape)
# Форма массива (shape) показывает размеры массива по всем измерениям, а его длина (len) — количество элементов только вдоль первой оси.

Массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Форма массива: (20,)


In [4]:
#1.2 Преобразуйте массив в матрицу размером 5x4. Проверьте результат.
import numpy as np
arr = np.arange(1, 21)
matrix = arr.reshape(5, 4)
print("Матрица 5x4:")
print(matrix)
print("Форма матрицы:", matrix.shape)
# Если число элементов в массиве не соответствует новой форме, функция reshape() вызовет ошибку

Матрица 5x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Форма матрицы: (5, 4)


In [7]:
#1.3 Увеличьте размерность массива до 20x1 с помощью np.newaxis и выведите форму нового массива.
import numpy as np
arr = np.arange(1, 21)
arr_reshaped = arr[:, np.newaxis]
print("Массив размером 20x1:")
print(arr_reshaped)
print("Форма массива:", arr_reshaped.shape)
# Увеличение размерности массива нужно для обеспечения совместимости с другими массивами 
#при математических операциях и подготовке данных к нужному формату, например, в машинном обучении.

Массив размером 20x1:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
Форма массива: (20, 1)


In [10]:
#2.1 Создайте массив из 12 равномерно распределенных значений в диапазоне [0, 5] с помощью np.linspace(). Преобразуйте его в матрицу 3x4.
import numpy as np
arr = np.linspace(0, 5, 12)
matrix = arr.reshape(3, 4)
print("Матрица 3x4 из равномерных значений:")
print(matrix)
# Линейное распределение создаёт равномерно расположенные точки на заданном интервале, 
#а случайное распределение генерирует точки в этом интервале в произвольном порядке без равномерности.


Матрица 3x4 из равномерных значений:
[[0.         0.45454545 0.90909091 1.36363636]
 [1.81818182 2.27272727 2.72727273 3.18181818]
 [3.63636364 4.09090909 4.54545455 5.        ]]


In [11]:
#2.2 Сгенерируйте матрицу 3x3 с: Случайными числами из равномерного распределения [0, 1).
# Случайными числами из нормального распределения. Целыми числами в диапазоне [1, 10].
import numpy as np

# Случайные числа из равномерного распределения [0, 1)
uniform_matrix = np.random.rand(3, 3)

# Случайные числа из нормального распределения (среднее=0, стандартное отклонение=1)
normal_matrix = np.random.randn(3, 3)

# Целые случайные числа в диапазоне [1, 10]
integer_matrix = np.random.randint(1, 11, size=(3, 3))

print("Матрица с равномерно распределёнными числами [0,1):\n", uniform_matrix)
print("\nМатрица с нормально распределёнными числами:\n", normal_matrix)
print("\nМатрица с целыми числами в диапазоне [1, 10]:\n", integer_matrix)

Матрица с равномерно распределёнными числами [0,1):
 [[0.95417088 0.68797746 0.25175731]
 [0.55905806 0.65478213 0.78190595]
 [0.78357027 0.11987859 0.76064422]]

Матрица с нормально распределёнными числами:
 [[ 0.99951793 -1.51826768 -0.0985058 ]
 [-1.06676293 -0.41247533  0.06060754]
 [ 0.14009345  0.44608216  1.12701676]]

Матрица с целыми числами в диапазоне [1, 10]:
 [[ 2  1  5]
 [ 3  4  8]
 [ 4 10  9]]


In [12]:
# 2.3 Сформируйте массив из 6 чисел по логарифмической шкале в диапазоне [10^1, 10^3] и преобразуйте его в двумерный массив 2x3
import numpy as np
log_array = np.logspace(1, 3, 6)
log_matrix = log_array.reshape(2, 3)
print("Массив по логарифмической шкале 2x3:")
print(log_matrix)
# Линейное распределение равномерно распределяет значения по интервалу, 
#логарифмическое — равномерно по логарифмической шкале, а геометрическое — описывает вероятность числа испытаний до первого успеха в серии событий.


Массив по логарифмической шкале 2x3:
[[  10.           25.11886432   63.09573445]
 [ 158.48931925  398.10717055 1000.        ]]


In [13]:
# 3.1 Создайте диагональную матрицу 4x4 с элементами [1, 2, 3, 4] на главной диагонали.
import numpy as np
diag_elements = [1, 2, 3, 4]
diag_matrix = np.diag(diag_elements)
print("Диагональная матрица 4x4:")
print(diag_matrix)
# Диагональная матрица используется для удобного представления и вычисления масштабирования, 
#преобразований и для упрощения операций с матрицами, поскольку умножение на диагональную матрицу сводится к поэлементному умножению по диагонали.

Диагональная матрица 4x4:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [14]:
# 3.2 Создайте единичную матрицу размера 5x5.
import numpy as np
identity_matrix = np.eye(5)
print("Единичная матрица 5x5:")
print(identity_matrix)
# не изменяет умножаемую матрицу

Единичная матрица 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# 3.3 Постройте
import numpy as np

# Нижнетреугольная матрица из чисел 1-16 в форме 4x4
arr1 = np.arange(1, 17).reshape(4, 4)
lower_triangular = np.tril(arr1)

# Верхнетреугольная матрица из чисел 1-25 в форме 5x5
arr2 = np.arange(1, 26).reshape(5, 5)
upper_triangular = np.triu(arr2)

print("Нижнетреугольная матрица 4x4:")
print(lower_triangular)

print("\nВерхнетреугольная матрица 5x5:")
print(upper_triangular)
# np.tril() оставляет нижнюю треугольную часть матрицы, а np.triu() — верхнюю, обнуляя остальные элементы.


Нижнетреугольная матрица 4x4:
[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]

Верхнетреугольная матрица 5x5:
[[ 1  2  3  4  5]
 [ 0  7  8  9 10]
 [ 0  0 13 14 15]
 [ 0  0  0 19 20]
 [ 0  0  0  0 25]]


In [21]:
# 4.1 Элементарные операции с матрицами
import numpy as np
m = int(input("Введите размер матриц m: "))
A = np.random.randint(1, 11, size=(m, m))
B = np.random.randint(1, 11, size=(m, m))
print("Матрица A:\n", A)
print("Матрица B:\n", B)
sum_matrix = A + B
print("\nСложение A + B:\n", sum_matrix)
sub_matrix = A - B
print("\nВычитание A - B:\n", sub_matrix)
mul_matrix = A * B
print("\nЭлементное умножение A * B:\n", mul_matrix)
div_matrix = A / B
print("\nЭлементное деление A / B:\n", div_matrix)

Введите размер матриц m:  4


Матрица A:
 [[2 2 7 8]
 [5 6 7 1]
 [8 1 4 9]
 [2 6 2 6]]
Матрица B:
 [[ 4  4  6  8]
 [ 2 10  2 10]
 [ 9  8  4  5]
 [ 8 10 10  5]]

Сложение A + B:
 [[ 6  6 13 16]
 [ 7 16  9 11]
 [17  9  8 14]
 [10 16 12 11]]

Вычитание A - B:
 [[-2 -2  1  0]
 [ 3 -4  5 -9]
 [-1 -7  0  4]
 [-6 -4 -8  1]]

Элементное умножение A * B:
 [[ 8  8 42 64]
 [10 60 14 10]
 [72  8 16 45]
 [16 60 20 30]]

Элементное деление A / B:
 [[0.5        0.5        1.16666667 1.        ]
 [2.5        0.6        3.5        0.1       ]
 [0.88888889 0.125      1.         1.8       ]
 [0.25       0.6        0.2        1.2       ]]


In [22]:
# 4.2
sqrt_matrix = np.sqrt(A)
print("\nКвадратный корень каждого элемента A:\n", sqrt_matrix)


Квадратный корень каждого элемента A:
 [[1.41421356 1.41421356 2.64575131 2.82842712]
 [2.23606798 2.44948974 2.64575131 1.        ]
 [2.82842712 1.         2.         3.        ]
 [1.41421356 2.44948974 1.41421356 2.44948974]]


In [23]:
# 4.3
transposed_B = B.T
print("\nТранспонированная матрица B:\n", transposed_B)


Транспонированная матрица B:
 [[ 4  2  9  8]
 [ 4 10  8 10]
 [ 6  2  4 10]
 [ 8 10  5  5]]


In [24]:
# 5.1 Создайте матрицу 4x4, где каждый элемент вычисляется как сумма его индексов. Используйте np.fromfunction().
import numpy as np
# Создание матрицы 4x4, где каждый элемент равен сумме его индексов
matrix = np.fromfunction(lambda i, j: i + j, (4, 4), dtype=int)
print("Матрица 4x4, где каждый элемент — сумма его индексов:\n", matrix)

Матрица 4x4, где каждый элемент — сумма его индексов:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [25]:
# 5.2 Постройте матрицу 3x3, где каждый элемент равен произведению индексов строки и столбца.
import numpy as np
matrix = np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)
print("Матрица 3x3 (произведение индексов строки и столбца):\n", matrix)

Матрица 3x3 (произведение индексов строки и столбца):
 [[0 0 0]
 [0 1 2]
 [0 2 4]]


In [26]:
# 6.1 Анализ элементов матрицы
import numpy as np
matrix = np.random.rand(5, 5)
print("Матрица 5x5:\n", matrix)
total_sum = np.sum(matrix)
print("\nСумма всех элементов:", total_sum)
row_sums = np.sum(matrix, axis=1)
print("\nСумма по строкам:", row_sums)
column_sums = np.sum(matrix, axis=0)
print("\nСумма по столбцам:", column_sums)

Матрица 5x5:
 [[0.03680161 0.42567198 0.68927222 0.22715454 0.16001742]
 [0.3993901  0.26553357 0.23465074 0.24893145 0.8647298 ]
 [0.96277412 0.99154161 0.49691696 0.51146312 0.69044624]
 [0.43590255 0.22708167 0.55871806 0.10501    0.7102931 ]
 [0.98470848 0.44024631 0.94372292 0.12958503 0.53032085]]

Сумма всех элементов: 12.270884440870658

Сумма по строкам: [1.53891776 2.01323566 3.65314204 2.03700539 3.02858359]

Сумма по столбцам: [2.81957687 2.35007513 2.9232809  1.22214414 2.95580741]


In [27]:
# 6.2 Анализ элементов матрицы
import numpy as np
matrix = np.random.rand(5, 5)
print("Матрица 5x5:\n", matrix)

# Сумма всех элементов
total_sum = np.sum(matrix)
print("\nСумма всех элементов:", total_sum)

# Сумма по строкам (axis=1)
row_sums = np.sum(matrix, axis=1)
print("\nСумма по строкам:", row_sums)

# Сумма по столбцам (axis=0)
column_sums = np.sum(matrix, axis=0)
print("\nСумма по столбцам:", column_sums)

Матрица 5x5:
 [[0.14319279 0.45689914 0.86602748 0.17127318 0.9184864 ]
 [0.15341817 0.07333492 0.45913537 0.2053014  0.28936726]
 [0.18641307 0.78440259 0.4468463  0.55902136 0.81644368]
 [0.60231462 0.03223581 0.65155554 0.86052299 0.70035607]
 [0.23618452 0.57878257 0.94334086 0.19685281 0.13242538]]

Сумма всех элементов: 11.464134281180089

Сумма по строкам: [2.55587899 1.18055711 2.793127   2.84698503 2.08758615]

Сумма по столбцам: [1.32152316 1.92565504 3.36690555 1.99297174 2.85707879]
